// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEZMRaCnY96JJHlTDxGnDyjaQprF_7pLY',
    appId: '1:715095642554:android:30b59481cfe5df30220d83',
    messagingSenderId: '715095642554',
    projectId: 'mentallyaiproject-8f49e',
    storageBucket: 'mentallyaiproject-8f49e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd5mrQOW8IWl2kEh2Y4csKV2MyxvFplCI',
    appId: '1:715095642554:ios:f536b7582af9bc47220d83',
    messagingSenderId: '715095642554',
    projectId: 'mentallyaiproject-8f49e',
    storageBucket: 'mentallyaiproject-8f49e.firebasestorage.app',
    iosClientId: '715095642554-of8fa95lfqtvnrgnseqhkjrm9kgq1s15.apps.googleusercontent.com',
    iosBundleId: 'com.futureitway.mentally',
  );
}
