// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQADCANXRqHiIF3z_wdix6K7g_wcUi49M',
    appId: '1:584316511993:web:ada1e849e805248d34a428',
    messagingSenderId: '584316511993',
    projectId: 'mental-health-app-85a6e',
    authDomain: 'mental-health-app-85a6e.firebaseapp.com',
    storageBucket: 'mental-health-app-85a6e.firebasestorage.app',
    measurementId: 'G-SBDSGMDXFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOMWcnCslSwEhw7455W61spp3PnSLL2W0',
    appId: '1:584316511993:android:70128f6d853abda234a428',
    messagingSenderId: '584316511993',
    projectId: 'mental-health-app-85a6e',
    storageBucket: 'mental-health-app-85a6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPGgmuamwItDIMkJCImuG0f-XHjLztSds',
    appId: '1:584316511993:ios:990933a40670334334a428',
    messagingSenderId: '584316511993',
    projectId: 'mental-health-app-85a6e',
    storageBucket: 'mental-health-app-85a6e.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDPGgmuamwItDIMkJCImuG0f-XHjLztSds',
  //   appId: '1:584316511993:ios:990933a40670334334a428',
  //   messagingSenderId: '584316511993',
  //   projectId: 'mental-health-app-85a6e',
  //   storageBucket: 'mental-health-app-85a6e.firebasestorage.app',
  //   iosBundleId: 'com.example.mentalHealthApp',
  // );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQADCANXRqHiIF3z_wdix6K7g_wcUi49M',
    appId: '1:584316511993:web:36be69c617b90c3934a428',
    messagingSenderId: '584316511993',
    projectId: 'mental-health-app-85a6e',
    authDomain: 'mental-health-app-85a6e.firebaseapp.com',
    storageBucket: 'mental-health-app-85a6e.firebasestorage.app',
    measurementId: 'G-XQ49J36EMT',
  );
}
